# Generated by Django 2.0.7 on 2019-06-08 21:36

from django.db import migrations, models
from ..models import ProductPrice


def create_product_prices(apps, schema_editor):
    ProductPrice(name='Standard', productCode='big_widget', price=100000).save()
    ProductPrice(name='Standard', productCode='sm_widget', price=9900).save()
    ProductPrice(name='Black Friday', productCode='big_widget', price=80000).save()
    ProductPrice(name='Black Friday', productCode='sm_widget', price=0).save()
    ProductPrice(name='2019', productCode='big_widget', price=120000).save()
    ProductPrice(name='2019', productCode='sm_widget', price=12500).save()
    print('### Migrations ###')


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productprice',
            old_name='code',
            new_name='productCode',
        ),
        migrations.RunPython(create_product_prices),
    ]
